version: '3.8'

services:
  auth-server:
    build: 
      context: ./auth
    container_name: auth-server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - rimo-network
    depends_on:
      - redis

  data-api-server:
    build: 
      context: ./data-api
    container_name: data-api-server
    environment:
      - SERVER_PORT=8081
      - DB_URL=jdbc:mariadb://211.46.52.166:13306/team4
      - DB_USERNAME=team4
      - DB_PASSWORD=Gkrtod1@
    networks:
      - rimo-network

  member-api-server:
    build: 
      context: ./member-api
    container_name: member-api-server
    environment:
      - SERVER_PORT=8082
      - DB_URL=jdbc:mariadb://211.46.52.166:13306/team4
      - DB_USERNAME=team4
      - DB_PASSWORD=Gkrtod1@
    networks:
      - rimo-network

  route-api-server:
    build: 
      context: ./route-api
    container_name: route-api-server
    environment:
      - SERVER_PORT=8083
      - DB_URL=jdbc:mariadb://211.46.52.166:13306/team4
      - DB_USERNAME=team4
      - DB_PASSWORD=Gkrtod1@
    networks:
      - rimo-network

  tracking-api-server:
    build:
      context: ./tracking-api
    container_name: tracking-api-server
    environment:
      - SERVER_PORT=8084
      - DB_URL=jdbc:mariadb://211.46.52.166:13306/team4
      - DB_USERNAME=team4
      - DB_PASSWORD=Gkrtod1@
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SOLAPI_API_KEY=NCSB2WWDSRDFQ5OL
      - SOLAPI_API_SECRET=KGAJWCCP8NMNNXMOQAK013LTCRFKDEK5
      - SOLAPI_SENDER=01037269288
      - KAKAO_REST_API_KEY=f5816278d02b2801c85fb59458782bee
    networks:
      - rimo-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: rimo-redis
    restart: unless-stopped
    networks:
      - rimo-network

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rimo-network
    depends_on:
      - auth-server
      - data-api-server
      - member-api-server
      - route-api-server
      - tracking-api-server
networks:
  rimo-network:
    driver: bridge
