services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    image: rimo-api
    container_name: rimo-api
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:mariadb://211.46.52.166:13306/team4
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
