server {
    listen 80;

    # 1. 인증 서버 (auth-api, 8080)
    # (실제 AuthApi.kt의 기본 주소에 맞춰 location 조정 필요)
    location /api/v1/auth/ { 
        proxy_pass http://auth-server:8080;
    }

    # 2. 리포트/데이터 서버 (data-api, 8081)
    location /api/report/ {
        proxy_pass http://data-api-server:8081;
    }

    # 3. 친구/회원 서버 (member-api, 8082)
    location /api/users {
        proxy_pass http://member-api-server:8082;
    }
    location /api/friends {
        proxy_pass http://member-api-server:8082;
    }
    location /api/member/ {
        proxy_pass http://member-api-server:8082;
    }
    location /api/guardians {
	proxy_pass http://member-api-server:8082;
    }

    # 4. 목적지/경로 서버 (route-api, 8083) - 수정된 경로 반영 완료
    location /api/route/ {
        proxy_pass http://route-api-server:8083;
    }
}
