server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://211.46.52.166:13306/team4
    username: team4
    password: Gkrtod1@
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # <--- [핵심] 대문자 이름을 그대로 쓰게 만드는 설정
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
