CREATE TABLE IF NOT EXISTS USR (
    MMBR_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    LGN_ID VARCHAR(50) NOT NULL UNIQUE,
    PWD VARCHAR(255) NOT NULL,
    MMBR_NM VARCHAR(50) NOT NULL,
    PRFL_CLR VARCHAR(20),
    MMBR_STTS_CD VARCHAR(10) NOT NULL,
    LGN_FL_CNT INT DEFAULT 0,
    LST_LGN_DT DATETIME,
    RGSTR_DT DATETIME DEFAULT CURRENT_TIMESTAMP,
    MDFY_DT DATETIME,
    US_YN CHAR(1) DEFAULT 'Y',
    DLT_YN CHAR(1) DEFAULT 'N'
);

CREATE TABLE IF NOT EXISTS FRND (
    FRND_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RQST_MMBR_ID BIGINT NOT NULL,
    RCV_MMBR_ID BIGINT NOT NULL,
    STTS_CD VARCHAR(10) NOT NULL,
    RQST_DT DATETIME,
    ACCPT_DT DATETIME,
    DLT_YN CHAR(1) DEFAULT 'N'
);

CREATE TABLE IF NOT EXISTS JRNY (
    JRNY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MMBR_ID BIGINT NOT NULL,
    STRT_ADDRSS VARCHAR(255),
    END_ADDRSS VARCHAR(255),
    STRT_LAT DECIMAL(10,7),
    STRT_LNG DECIMAL(10,7),
    END_LAT DECIMAL(10,7),
    END_LNG DECIMAL(10,7),
    PTH_TYP_CD VARCHAR(10),
    STTS_CD VARCHAR(10),
    STRT_DT DATETIME,
    END_DT DATETIME
);
