spring.application.name=route-api
server.port=${SERVER_PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.open-in-view=false

kakao.mobility.rest-api-key=${KAKAO_MOBILITY_REST_API_KEY}

data-api.base-url=${DATA_API_BASE_URL:http://data-api-server:8084}


gemini.model=gemini-3.6-flash
gemini.api-key=${GEMINI_API_KEY}
